const sample = {
  appUserId: "1",
  modelPatientList: [
    {
      modelVisitList: [
        {
          modelVisitSafe: {
            checkup: {
              _checkup_dbp: "88mmHg",
              _checkup_id: 2,
              _checkup_risk: "YES",
              _checkup_risk_sign: '["Bleeding per vagina","Leaking, Cramps"]',
              _checkup_sbp: "123mmHg",
              _visit_patient_detail_patient_detail_id: 2,
              _visit_patient_detail_ward_ward_id: 8,
              _visit_visit_id: 2,
            },
            conceptionRecord: {
              _conception_record_id: 0,
              _visit_patient_detail_patient_detail_id: 0,
              _visit_patient_detail_ward_ward_id: 0,
              _visit_visit_id: 0,
            },
            deliveryDetail: {
              _delivery_detail_id: 0,
              _visit_patient_detail_patient_detail_id: 0,
              _visit_patient_detail_ward_ward_id: 0,
              _visit_visit_id: 0,
            },
            healthDetail: {
              _health_detail_id: 1,
              _health_detail_previous_visit: "NO",
              _visit_patient_detail_patient_detail_id: 2,
              _visit_patient_detail_ward_ward_id: 8,
              _visit_visit_id: 2,
            },
            lab: {
              _lab_id: 0,
              _visit_patient_detail_patient_detail_id: 0,
              _visit_patient_detail_ward_ward_id: 0,
              _visit_visit_id: 0,
            },
            menstrualDate: {
              _menstrual_date_id: 0,
              _patient_detail_patient_detail_id: 0,
              _patient_detail_ward_ward_id: 0,
            },
            pregnancyHistory: {
              _patient_detail_patient_detail_id: 0,
              _patient_detail_ward_ward_id: 0,
              _pregnancy_history_id: 0,
            },
            pregnancyTermination: "NO",
            preventiveCare: {
              _preventive_care_id: 0,
              _visit_patient_detail_patient_detail_id: 0,
              _visit_patient_detail_ward_ward_id: 0,
              _visit_visit_id: 0,
            },
            termination: {
              _termination_id: 0,
              _visit_patient_detail_patient_detail_id: 0,
              _visit_patient_detail_ward_ward_id: 0,
              _visit_visit_id: 0,
            },
            usg: {
              _usg_id: 0,
              _visit_patient_detail_patient_detail_id: 0,
              _visit_patient_detail_ward_ward_id: 0,
              _visit_visit_id: 0,
            },
            visitTime: "zero_to_third_R",
            visitType: "REGULAR",
          },
          patient_id: 1,
          visit_category: "SAFE_MOTHERHOOD",
          visit_followupdate_english: "20/20/20",
          visit_followupdate_nepali: "20/20/20",
          visit_id: 2,
          visit_lastdate_english: "20/20/20",
          visit_lastdate_nepali: "20/20/20",
          ward: 1,
        },
      ],
      patientAddedDate: "01/27/2021 12:43:07",
      patientAge: "23",
      patientDob: "27/01/1998",
      patientFirstName: "Rita",
      patientFullName: "Rita shakya",
      patientGender: "Female",
      patientHouseno: "23-23",
      patientId: 1,
      patientLastName: "shakya",
      patientMunicipality: "ktm",
      patientPhone: "9852232102",
      patientSpouseFullName: "hus band",
      patientVillagename: "Village 1",
      patientspousefirstname: "hus",
      patientspouselastname: "band",
      patientwardno: 1,
    },
    {
      modelVisitList: [
        {
          modelVisitSafe: {
            checkup: {
              _checkup_dbp: "88mmHg",
              _checkup_id: 2,
              _checkup_risk: "YES",
              _checkup_risk_sign: '["Bleeding per vagina","Leaking, Cramps"]',
              _checkup_sbp: "123mmHg",
              _visit_patient_detail_patient_detail_id: 2,
              _visit_patient_detail_ward_ward_id: 8,
              _visit_visit_id: 2,
            },
            conceptionRecord: {
              _conception_record_id: 0,
              _visit_patient_detail_patient_detail_id: 0,
              _visit_patient_detail_ward_ward_id: 0,
              _visit_visit_id: 0,
            },
            deliveryDetail: {
              _delivery_detail_id: 0,
              _visit_patient_detail_patient_detail_id: 0,
              _visit_patient_detail_ward_ward_id: 0,
              _visit_visit_id: 0,
            },
            healthDetail: {
              _health_detail_id: 1,
              _health_detail_previous_visit: "NO",
              _visit_patient_detail_patient_detail_id: 2,
              _visit_patient_detail_ward_ward_id: 8,
              _visit_visit_id: 2,
            },
            lab: {
              _lab_id: 0,
              _visit_patient_detail_patient_detail_id: 0,
              _visit_patient_detail_ward_ward_id: 0,
              _visit_visit_id: 0,
            },
            menstrualDate: {
              _menstrual_date_id: 0,
              _patient_detail_patient_detail_id: 0,
              _patient_detail_ward_ward_id: 0,
            },
            pregnancyHistory: {
              _patient_detail_patient_detail_id: 0,
              _patient_detail_ward_ward_id: 0,
              _pregnancy_history_id: 0,
            },
            pregnancyTermination: "NO",
            preventiveCare: {
              _preventive_care_id: 0,
              _visit_patient_detail_patient_detail_id: 0,
              _visit_patient_detail_ward_ward_id: 0,
              _visit_visit_id: 0,
            },
            termination: {
              _termination_id: 0,
              _visit_patient_detail_patient_detail_id: 0,
              _visit_patient_detail_ward_ward_id: 0,
              _visit_visit_id: 0,
            },
            usg: {
              _usg_id: 0,
              _visit_patient_detail_patient_detail_id: 0,
              _visit_patient_detail_ward_ward_id: 0,
              _visit_visit_id: 0,
            },
            visitTime: "zero_to_third_R",
            visitType: "REGULAR",
          },
          patient_id: 2,
          visit_category: "SAFE_MOTHERHOOD",
          visit_followupdate_english: "20/20/20",
          visit_followupdate_nepali: "20/20/20",
          visit_id: 2,
          visit_lastdate_english: "20/20/20",
          visit_lastdate_nepali: "20/20/20",
          ward: 8,
        },
      ],
      patientAddedDate: "01/27/2021 16:39:28",
      patientAge: "25",
      patientDob: "27/01/1996",
      patientFirstName: "Sita",
      patientFullName: "Sita Shrestha",
      patientGender: "Female",
      patientHouseno: "232323",
      patientId: 2,
      patientLastName: "Shrestha",
      patientMunicipality: "kathamndu",
      patientPhone: "9803354191",
      patientSpouseFullName: "husnamdname lasthusbandnamme",
      patientVillagename: "Village 7",
      patientspousefirstname: "husnamdname",
      patientspouselastname: "lasthusbandnamme",
      patientwardno: 8,
    },
  ],
};
